### PR TITLE
Fixed #21 #23 and updated dependencies

### LINKED ISSUE #21: SQL time out issue
**Describe the bug**
SQL time out issue on MySQL
LOG: https://sourceb.in/S2Pnkxf107

**To Reproduce**
1. Join the server
2. Leave from the server.
3. See an error https://sourceb.in/S2Pnkxf107

**Expected behavior**
No error on the console and the data should be saved!

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Server software Paper
 - Server Version 1.8.9
 - Plugin Version 21.10.1

### PR DESCRIPTION
**Pull request by MherZaqaryan**

### CODE REVIEW

File: bedwars-plugin/src/main/java/com/andrei1058/bedwars/database/MySQL.java [hunk 1]
```diff
@@ -241,7 +241,7 @@ public PlayerStats fetchStats(UUID uuid) {
 
     @Override
     public void setQuickBuySlot(UUID uuid, String shopPath, int slot) {
-        String sql = "SELECT id FROM quick_buy_2 WHERE uuid = ?;";
+        String sql = "SELECT * FROM quick_buy_2 WHERE uuid = ?;";
```
Comment (andrei1058) [inline bedwars-plugin/src/main/java/com/andrei1058/bedwars/database/MySQL.java]: replace * with a column name, uuid

**Review by andrei1058 — COMMENTED** [review]
I'm not sure if it is good practice to close the sql lite connection since we may have many transactions on a medium player base and may result in useless cpu usage for try-closing every single time.
